apiVersion: v1
kind: Service
metadata:
  name: addressbook
  labels:
    role: addressbook
spec:
  selector:
    role: addressbook
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  type: LoadBalancer
