apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook
  labels:
    role: addressbook
spec:
  replicas: 12
  selector:
    matchLabels:
      role: addressbook
  template:
    metadata:
      name: addressbook
      labels:
        role: addressbook
    spec:
      containers:
        - name: app
          image: sivaplv30/addressbook:latest
