apiVersion: v1
kind: Service
metadata:
  name: ab-service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  ports:
  - port: 49153
    targetPort: 49153
    type: LoadBalancer
    selector:
      name: addressbook
      app: addressbook
