apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook
  labels:
    role: addressbook
spec:
  minReadySeconds: 20
  replicas: 3
  selector:
    matchLabels:
      role: addressbook
  template:
    metadata:
      name: addressbook
      labels:
        app: addressbook
        role: addressbook
    spec:
      containers:
        - name: addressbook
          image: sivaplv30/addressbook:latest
