apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab
  labels:
    role: ab
spec:
  replicas: 3
  selector:
    matchLabels:
      role: ab 
  template:
    metadata:
      name: ab
    spec:
      containers:
        - name: addressbook
          image: sivaplv30/addressbook:latest
